# Assignment Numpy

## Q1.Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does itenhance Python's capabilities for numerical operations?

### Answer:-

#### NumPy (Numerical Python) is a powerful library in Python, widely used in scientific computing and data analysis due to its efficient handling of large datasets and support for high-performance mathematical operations.

#### Purpose of NumPy:

Efficient Array Handling: NumPy provides a multidimensional array object called ndarray, which can handle large datasets much more efficiently than Python’s built-in lists.

Mathematical and Statistical Functions: It includes a wide range of built-in mathematical operations like matrix multiplication, Fourier transforms, linear algebra, and random number generation, which are essential in scientific computing.

Data Manipulation: NumPy is designed for fast data manipulation and computation. It allows slicing, indexing, and reshaping of arrays, making data manipulation easy and intuitive.

Foundation for Other Libraries: NumPy serves as the backbone for many other popular Python libraries used in data science and machine learning, such as Pandas, SciPy, Matplotlib, and

#### Advantages of NumPy:

Speed and Performance: NumPy is significantly faster than native Python data structures (like lists and dictionaries) because it is implemented in C and allows for vectorized operations, avoiding loops and improving speed.

Memory Efficiency: NumPy arrays consume less memory compared to Python lists due to their fixed data types, allowing for more efficient use of memory when handling large datasets.

Vectorization: NumPy allows for vectorized operations, meaning you can perform element-wise operations on entire arrays without writing explicit loops. This makes the code more concise and reduces execution time.

Multidimensional Arrays: It supports multidimensional arrays, which are crucial for handling complex datasets like matrices, tensors, or grids of data in scientific computing.

Broadcasting: NumPy allows operations on arrays of different shapes and sizes using a technique called broadcasting, which simplifies many mathematical operations and avoids the need for manually reshaping arrays.

Interoperability: It integrates seamlessly with other scientific computing libraries (such as Pandas for data manipulation or Matplotlib for data visualization), enhancing Python’s overall capabilities.

#### How It Enhances Python’s Capabilities for Numerical Operations:

Faster Computation: Python's standard operations with lists or loops can be slow, but NumPy leverages optimized C-based algorithms for faster execution of numerical tasks.

Handling Large Data: NumPy allows users to handle large-scale datasets efficiently, which is essential for data analysis tasks in fields like machine learning, deep learning, and scientific simulations.

Mathematical Operations: With functions like dot(), sum(), mean(), and many others, NumPy simplifies complex mathematical operations without requiring manual implementation.

Data Transformation and Analysis: NumPy makes it easy to reshape, transpose, and aggregate data, enabling more effective analysis and transformation of datasets.

## Q2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

### Answer:-

#### In NumPy, both np.mean() and np.average() are used to compute the average of an array, but they have some differences in functionality and use cases. Here’s a comparison of the two:

#### 1. Basic Functionality:

np.mean(): This function calculates the arithmetic mean (average) of the elements along a specified axis (or the whole array if no axis is specified).

np.average(): Similar to np.mean(), but it offers an additional feature where you can specify weights for the elements in the array. This allows for the calculation of a weighted average.

#### 2. Syntax:


In [2]:
#np.mean()

#np.mean(array, axis=None)

#array: Input array or list.

#axis: The axis along which the mean is computed. If none is specified, the mean is calculated over the flattened array

In [7]:
#np.average()

#np.average(array, axis=None, weights=None)

#array: Input array or list.

#axis: The axis along which the average is computed. If none is specified, the average is calculated over the flattened array.

#weights: An array of the same shape as array that assigns a weight to each element for computing a weighted average. If not provided, it behaves like np.mean() and calculates a simple mean."""

#### 3. Weighted Averages:

np.mean(): Does not support weights; it always computes the simple arithmetic mean.

np.average(): Supports weights. If you provide a weights argument, np.average() will compute a weighted average. If no weights are given, it defaults to calculating the arithmetic mean, like np.mean().

In [10]:
import numpy as np

In [11]:
arr = np.array([1, 2, 3, 4])
weights = np.array([1, 2, 3, 4])
np.average(arr, weights=weights)  # Output: 3.0 (Weighted average)


np.float64(3.0)

#### 4. Return Type:

Both np.mean() and np.average() return the same type: a scalar value if computed over all elements, or an array if computed along a specific axis.

#### 5. Performance:

When no weights are used, both functions perform similarly because np.average() defaults to a simple mean calculation.

When weights are used in np.average(), it might introduce a slight overhead due to the additional calculations involving weights.

#### When to Use One Over the Other:

Use np.mean():

When you only need to calculate the simple arithmetic mean of an array.

It's a more straightforward and slightly more efficient choice when you don't need weighted averages.

Use np.average():

When you need to compute a weighted average.

If you need the flexibility of adding weights to different elements in your array.

In [15]:
#np.mean() Example:
arr = np.array([1, 2, 3, 4])
np.mean(arr)  # Output: 2.5 (Arithmetic mean)



np.float64(2.5)

In [14]:
#np.average() Example (Simple Mean):
arr = np.array([1, 2, 3, 4])
np.average(arr)  # Output: 2.5 (Same result as np.mean() without weights)



np.float64(2.5)

In [13]:
#np.average() Example (Weighted Mean):
arr = np.array([1, 2, 3, 4])
weights = np.array([1, 2, 3, 4])
np.average(arr, weights=weights)  # Output: 3.0 (Weighted average)


np.float64(3.0)

## Q3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

### Answer:-

#### In NumPy, you can reverse arrays along different axes using slicing, the numpy.flip() function, and numpy.fliplr() or numpy.flipud() for specific axis reversals. Let's explore these methods with examples for 1D and 2D arrays:

### 1. Reversing a 1D NumPy Array:

A 1D array can be reversed simply by slicing or using the numpy.flip() function.

### Method 1: Slicing

In [16]:
import numpy as np

# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reversing the array using slicing
reversed_arr_1d = arr_1d[::-1]

print(reversed_arr_1d)


[5 4 3 2 1]


### Method 2: Using numpy.flip()

In [17]:
# Reversing the array using numpy.flip()
reversed_arr_1d_flip = np.flip(arr_1d)

print(reversed_arr_1d_flip)


[5 4 3 2 1]


### 2. Reversing a 2D NumPy Array:

For 2D arrays, you can reverse along specific axes (rows or columns) or reverse the entire array.

### Method 1: Reverse along rows (axis 1)



In [21]:
#Example of 2D Array 
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])



In [22]:
# Using slicing
reversed_rows = arr_2d[:, ::-1]

print(reversed_rows)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


### Method 2: Reverse along columns (axis 0)

In [23]:
# Using slicing
reversed_columns = arr_2d[::-1, :]

print(reversed_columns)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


### Method 3: Using numpy.flip()

The numpy.flip() function can be used to reverse along any axis. You can specify the axis with the axis parameter.

In [25]:

#Reverse along axis 0 (rows):
reversed_2d_axis0 = np.flip(arr_2d, axis=0)
print(reversed_2d_axis0)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [26]:
#Reverse along axis 1 (columns):
reversed_2d_axis1 = np.flip(arr_2d, axis=1)
print(reversed_2d_axis1)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


### Method 4: Using numpy.fliplr() and numpy.flipud()

numpy.fliplr() reverses the array from left to right (reverses the columns):

In [27]:
reversed_lr = np.fliplr(arr_2d)
print(reversed_lr)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


#### 
numpy.flipud() reverses the array from top to bottom (reverses the rows):

In [28]:
reversed_ud = np.flipud(arr_2d)
print(reversed_ud)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


## Q4.How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

### Answer:-

### Determining the Data Type of Elements in a NumPy Array

To determine the data type of elements in a NumPy array, you can use the .dtype attribute of the array.

In [29]:
#Example
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4])

# Determining the data type of the array elements
print(arr.dtype)


int64


####
This shows that the elements in the array are of type int64. The .dtype attribute provides information about the type of data stored in the array, such as integers, floats, or more complex types like strings or custom objects.

### Importance of Data Types in Memory Management and Performance

#### 1. Memory Efficiency

Each data type consumes a specific amount of memory. Using the appropriate data type ensures that memory is not wasted on unnecessary precision. For example:

int8 requires 1 byte of memory for each element.

int32 requires 4 bytes.

float64 requires 8 bytes.

If you need to store small integers (like 0-255), using int64 would waste memory compared to int8. In cases where large datasets are involved, selecting the correct data type can lead to significant memory savings.

In [30]:
#Example of Memory Usage:
# Array of integers
arr_int8 = np.array([1, 2, 3, 4], dtype=np.int8)
arr_int64 = np.array([1, 2, 3, 4], dtype=np.int64)

print(arr_int8.nbytes)  # Memory usage for int8
print(arr_int64.nbytes)  # Memory usage for int64


4
32


#### 
If you run this, you’ll see that arr_int8 uses 4 bytes, whereas arr_int64 uses 32 bytes for the same data. Choosing the correct data type saves memory.

#### 2. Performance Optimization

The data type also impacts the speed of computations. Operations on smaller, simpler data types are generally faster because they require fewer resources (both in terms of memory and CPU cycles). This is particularly relevant in high-performance computing tasks where large datasets are processed.


For example, if you perform mathematical operations on arrays of int8 vs. int64, the former will often be faster since less data is transferred and processed.

In [33]:
import numpy as np
import time

# Create a large array with int8
arr_small = np.random.randint(-128, 128, size=10000000, dtype=np.int8)

# Create a large array with int64
arr_large = np.random.randint(0, 256, size=10000000, dtype=np.int64)

# Measure the time taken for an operation (adding 1) on int8 array
start_time = time.time()
result_small = arr_small + 1
print(f"Time taken for int8 array: {time.time() - start_time:.6f} seconds")

# Measure the time taken for the same operation on int64 array
start_time = time.time()
result_large = arr_large + 1
print(f"Time taken for int64 array: {time.time() - start_time:.6f} seconds")


Time taken for int8 array: 0.009852 seconds
Time taken for int64 array: 0.039235 seconds


#### 
You will notice that operations on arr_small (with int8) are faster than on arr_large (with int64).

### 3. Precision and Accuracy

For floating-point numbers, selecting the appropriate data type affects the precision of the calculations. float32 offers less precision than float64. For applications requiring high precision, such as scientific calculations, using a higher-precision data type (e.g., float64) is crucial. On the other hand, for tasks where precision is not as critical, using float32 can save memory and improve performance.

### 4. Compatibility and Flexibility

Different systems and libraries may have requirements for specific data types. Ensuring that data types match across different components of an application avoids compatibility issues. For example, certain machine learning libraries may require inputs to be in a specific format (e.g., float32).

## Q5.Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

### Answer:-

### Definition of ndarrays in NumPy

In NumPy, an ndarray (N-dimensional array) is a powerful and flexible data structure that represents a multidimensional, homogeneous collection of items. It is the core data structure of the NumPy library and is designed for efficient storage and manipulation of numerical data.

### Key Features of ndarrays

N-dimensional:

An ndarray can have any number of dimensions (1D, 2D, 3D, etc.). The number of dimensions is referred to as the rank of the array.

Homogeneous:

All elements in an ndarray must be of the same data type (e.g., all integers, all floats). This uniformity allows for efficient memory usage and performance optimization.

Fixed Size:

Once an ndarray is created, its size (number of elements) cannot be changed. This fixed size allows for efficient memory allocation and manipulation.

Efficient Memory Usage:

NumPy ndarrays are more memory-efficient than standard Python lists, especially for large datasets, because they store data in contiguous blocks of memory.

Broadcasting:

NumPy allows operations on arrays of different shapes through broadcasting, which automatically expands the smaller array to match the shape of the larger array.

Vectorized Operations:

Ndarrays support element-wise operations and mathematical functions directly, enabling fast computations without the need for explicit loops, leveraging optimized C and Fortran libraries under the hood.

Multidimensional Slicing:

Ndarrays allow for advanced indexing and slicing, enabling users to access and modify subsets of the array easily.
Built-in Mathematical Functions:

NumPy provides a wide array of mathematical functions (e.g., sum, mean, standard deviation) that operate directly on ndarrays, enhancing productivity and performance.

### Differences Between ndarrays and Standard Python Lists

| Feature                     | ndarrays                                 | Standard Python Lists                       |
|-----------------------------|------------------------------------------|---------------------------------------------|
| **Homogeneity**             | Must contain elements of the same type  | Can contain elements of different types     |
| **Memory Efficiency**       | More memory-efficient; contiguous memory | Less memory-efficient; fragmented memory     |
| **Performance**             | Faster for numerical operations          | Slower for numerical operations; loop-based  |
| **N-dimensional**           | Can be multi-dimensional (2D, 3D, etc.)| Primarily one-dimensional (nested lists can create 2D, 3D, etc.) |
| **Fixed Size**              | Size is fixed after creation             | Can grow and shrink dynamically              |
| **Operations**              | Supports vectorized operations           | Requires explicit loops for operations       |
| **Built-in Functions**      | Extensive mathematical functions available| Limited to basic Python operations           |
| **Broadcasting**            | Supports broadcasting                     | No broadcasting capabilities                  |


#### Example Comparison
Ndarray Example:

In [35]:
import numpy as np

# Create a 2D ndarray
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Perform a vectorized operation
result = arr + 10  # Adds 10 to each element
print(result)


[[11 12 13]
 [14 15 16]]


#### 
Python List Example:

In [34]:
# Create a nested Python list
lst = [[1, 2, 3], [4, 5, 6]]

# Perform an operation using a loop
result_list = [[x + 10 for x in sublist] for sublist in lst]
print(result_list)


[[11, 12, 13], [14, 15, 16]]


## Q6.Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

### Answer:-

### Performance Benefits of NumPy Arrays Over Python Lists for Large-Scale Numerical Operations

NumPy arrays offer significant performance advantages over standard Python lists, particularly in the context of large-scale numerical operations. Below are the key benefits, explained in detail:

#### 1. Memory Efficiency

Contiguous Memory Allocation: NumPy arrays are stored in contiguous blocks of memory, which reduces overhead and improves cache performance. In contrast, Python lists are dynamic arrays that can store objects of different sizes, leading to fragmented memory allocation.

Homogeneous Data Types: All elements in a NumPy array must be of the same data type. This uniformity allows NumPy to allocate the exact amount of memory required for the data, whereas Python lists must allocate memory for each element individually, which can lead to higher memory usage.


#### 2. Speed of Operations

Vectorized Operations: NumPy allows for vectorized operations that perform element-wise computations directly on the entire array without the need for explicit loops. This can lead to performance improvements of orders of magnitude. For instance, adding two arrays can be done in a single operation rather than iterating through each element.

In [36]:
#Example
import numpy as np

# NumPy array
arr = np.arange(1000000)

# Vectorized addition
result = arr + 1  # Faster than using a loop


#### 
Optimized Algorithms: NumPy is implemented in C and uses optimized libraries (like BLAS and LAPACK) for linear algebra operations. These libraries are highly efficient for numerical calculations and take advantage of hardware capabilities.

#### 3. Reduced Overhead

Less Overhead in Operations: When performing mathematical operations, NumPy arrays have less overhead compared to Python lists, which require type checks and object management. NumPy can leverage lower-level optimizations and perform computations more directly.

#### 4. Broadcasting Capabilities

Flexible Arithmetic: NumPy supports broadcasting, which allows arithmetic operations on arrays of different shapes and sizes without the need for explicit replication of data. This feature simplifies code and improves performance.

In [41]:
# Example of broadcasting
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

# Broadcasting: a (1D) is added to each row of b (2D)
result = a + b


#### 5. Support for Multi-dimensional Arrays

N-dimensional Arrays: NumPy can handle multi-dimensional arrays (e.g., 2D, 3D), enabling efficient representation and manipulation of large datasets (like images, matrices, etc.). Operations on these arrays are optimized for speed and memory efficiency.

#### 6. Built-in Mathematical Functions

Rich Library of Functions: NumPy provides a wide range of built-in mathematical functions that operate directly on arrays, including statistical functions, linear algebra routines, and more. These functions are highly optimized and often faster than custom implementations using Python lists.

In [40]:
# Example of using NumPy functions
mean_value = np.mean(arr)  # Fast calculation of mean


#### 7. Parallel Processing

Potential for Parallelism: NumPy operations can take advantage of parallel processing capabilities of modern CPUs, especially when using libraries like Numexpr or Dask. This further enhances performance for large datasets.

In [39]:
"""Comparative Example
Here's a simple comparative performance benchmark using NumPy arrays and Python lists for a large-scale operation (summing two arrays):"""

import numpy as np
import time

# Creating large data sets
size = 10**7
list1 = list(range(size))
list2 = list(range(size))

array1 = np.arange(size)
array2 = np.arange(size)

# Timing Python list addition
start_time = time.time()
list_sum = [x + y for x, y in zip(list1, list2)]
print(f"List addition time: {time.time() - start_time:.6f} seconds")

# Timing NumPy array addition
start_time = time.time()
array_sum = array1 + array2
print(f"NumPy addition time: {time.time() - start_time:.6f} seconds")


List addition time: 2.996628 seconds
NumPy addition time: 0.357970 seconds


## Q7.Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

### Answer:-

#### In NumPy, vstack() and hstack() are functions used to stack arrays in different dimensions. Here’s a detailed comparison of both functions, along with examples demonstrating their usage.

#### 1. vstack()

Description:

vstack() stands for "vertical stack." It stacks arrays vertically (row-wise) along the first axis (axis 0). This means that it combines arrays by adding new rows.

Usage:

All input arrays must have the same shape along all but the first axis (i.e., the number of columns must be the same).

In [43]:
#Example of vstack()
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2, 3], 
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9], 
                   [10, 11, 12]])

# Using vstack to stack the arrays vertically
result_vstack = np.vstack((array1, array2))
print("Result of vstack:\n", result_vstack)


Result of vstack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 2. hstack()

Description:

hstack() stands for "horizontal stack." It stacks arrays horizontally (column-wise) along the second axis (axis 1). This means that it combines arrays by adding new columns.

Usage:

All input arrays must have the same shape along all but the second axis (i.e., the number of rows must be the same).

In [44]:
#Example of hstack()
# Using hstack to stack the arrays horizontally
result_hstack = np.hstack((array1, array2))
print("Result of hstack:\n", result_hstack)


Result of hstack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### Summary of Differences

| Feature                     | vstack()                              | hstack()                              |
|-----------------------------|---------------------------------------|---------------------------------------|
| **Stacking Direction**      | Vertical (row-wise)                  | Horizontal (column-wise)              |
| **Input Shape Requirement** | Same number of columns                | Same number of rows                   |
| **Axis**                    | Stacks along the first axis (axis 0) | Stacks along the second axis (axis 1) |


## Q8.Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

### Answer:-

#### In NumPy, fliplr() and flipud() are functions used to flip arrays in different directions. Here’s a detailed explanation of the differences between these two methods, including their effects on various array dimensions

#### 1. fliplr()

Description:

fliplr() stands for "flip left to right." This function flips an array in the left-right direction, meaning that the columns of the array are reversed.

Usage:

It operates along the second axis (axis 1) and is primarily used for 2D arrays. However, it can also work on 1D and higher-dimensional arrays, where the flipping is applied to the last dimension.

In [47]:
#Example of fliplr()
import numpy as np

# Creating a 2D array
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6]])

# Using fliplr to flip the array
flipped_lr = np.fliplr(array_2d)
print("Flipped left to right:\n", flipped_lr)


Flipped left to right:
 [[3 2 1]
 [6 5 4]]


#### 2. flipud()
Description:

flipud() stands for "flip up to down." This function flips an array in the up-down direction, meaning that the rows of the array are reversed.

Usage:

It operates along the first axis (axis 0) and is primarily used for 2D arrays. Similar to fliplr(), it can also be applied to higher-dimensional arrays, flipping along the first dimension.

In [48]:
#Example of flipud()
# Using flipud to flip the array
flipped_ud = np.flipud(array_2d)
print("Flipped up to down:\n", flipped_ud)


Flipped up to down:
 [[4 5 6]
 [1 2 3]]


## Differences

| Feature                   | `fliplr()`                             | `flipud()`                             |
|---------------------------|----------------------------------------|----------------------------------------|
| **Description**           | Flips an array left to right (columns reversed) | Flips an array up to down (rows reversed) |
| **Direction of Flip**     | Left to right                          | Up to down                             |
| **Axis**                  | Operates along the second axis (axis 1) | Operates along the first axis (axis 0) |
| **Effect on 2D Arrays**   | Reverses the order of columns          | Reverses the order of rows             |
| **Effect on 1D Arrays**  | Raises ValueError (requires 2D input) | Raises ValueError (requires 2D input) |
| **Higher Dimensions**     | Flips along the last axis              | Flips along the first axis             |
| **Equivalent Function for 1D** | Not applicable (use `np.flip()`)  | Not applicable (use `np.flip()`)      |


### Effects on Various Array Dimensions

1D Arrays:

For 1D arrays, both fliplr() and flipud() behave the same as flip(), reversing the order of elements.

In [50]:
import numpy as np

# Example with a 1D array
arr_1d = np.array([1, 2, 3])

# Using np.flip() to flip the 1D array
flipped = np.flip(arr_1d)  # Equivalent to both fliplr and flipud for 1D
print(flipped)  # Output: [3 2 1]


[3 2 1]


#### 
2D Arrays:

fliplr() flips columns, while flipud() flips rows.

Higher-dimensional Arrays:

In 3D or higher-dimensional arrays, fliplr() will flip the last dimension (like columns), and flipud() will flip the first dimension (like rows).

In [51]:
#Example of Both fliplr() and flipud() with 2D Arrays
# Example with a 2D array
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6]])

# Flipping left to right
flipped_lr = np.fliplr(array_2d)
print("Flipped left to right:\n", flipped_lr)

# Flipping up to down
flipped_ud = np.flipud(array_2d)
print("Flipped up to down:\n", flipped_ud)


Flipped left to right:
 [[3 2 1]
 [6 5 4]]
Flipped up to down:
 [[4 5 6]
 [1 2 3]]


## Q9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

### Answer:-

#### The array_split() method in NumPy is a powerful function used to split an array into multiple sub-arrays. Unlike split(), which requires the splits to be of equal size, array_split() can handle uneven splits, making it more versatile for different use cases.

### Functionality of array_split() :- 

### Basic Syntax :-

numpy.array_split(ary, indices_or_sections, axis=0)

Parameters:

ary: The input array to be split.

indices_or_sections: This can be an integer or a sequence. If an integer is provided, it specifies the number of equal sections to split the array into. If a sequence is given, it indicates the specific indices at which to split the array.

axis: The axis along which to split the array. The default is 0 (along rows).

#### 
Return Value

The function returns a list of sub-arrays, which are the result of the split operation.

#### Handling Uneven Splits

When the number of elements in the original array is not perfectly divisible by the number of sections requested, array_split() handles the situation gracefully by distributing the elements as evenly as possible among the sub-arrays.

In [55]:
#Example of Uneven Splits
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7])

# Split the array into 3 sections
split_arrays = np.array_split(array_1d, 3)

print("Original Array:", array_1d)
print("Split Arrays:")
for i, sub_array in enumerate(split_arrays):
    print(f"Sub-array {i}: {sub_array}")


Original Array: [1 2 3 4 5 6 7]
Split Arrays:
Sub-array 0: [1 2 3]
Sub-array 1: [4 5]
Sub-array 2: [6 7]


In [56]:
#Additional Example with 2D Arrays
#You can also use array_split() on 2D arrays:

# Create a 2D array
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9], 
                     [10, 11, 12]])

# Split the array into 3 sections along the first axis (rows)
split_2d_arrays = np.array_split(array_2d, 3, axis=0)

print("Original 2D Array:\n", array_2d)
print("Split 2D Arrays:")
for i, sub_array in enumerate(split_2d_arrays):
    print(f"Sub-array {i}:\n{sub_array}")


Original 2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Split 2D Arrays:
Sub-array 0:
[[1 2 3]
 [4 5 6]]
Sub-array 1:
[[7 8 9]]
Sub-array 2:
[[10 11 12]]


## Q10.Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

### Answer:-

#### Vectorization and broadcasting are two powerful concepts in NumPy that significantly enhance the efficiency of array operations. These concepts allow for fast computations by leveraging underlying optimizations and avoiding the need for explicit loops in Python code

#### 1. Vectorization

Definition: Vectorization is the process of converting operations on scalar values (individual elements) into operations on entire arrays (or vectors). In NumPy, vectorized operations enable you to perform element-wise operations on arrays without the need for explicit loops.

#### Key Features:

Element-wise Operations: NumPy automatically applies operations to each element of the array.

Performance: Vectorized operations are generally much faster than equivalent operations done with Python loops because NumPy uses optimized C and Fortran libraries under the hood.

Readable Code: Vectorized operations lead to more concise and readable code.

In [57]:
#Example
import numpy as np

# Create two arrays
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Vectorized addition
result = a + b  # Adds corresponding elements of a and b
print(result)  # Output: [11 22 33 44]


[11 22 33 44]


#### 2. Broadcasting

Definition: Broadcasting is a feature that allows NumPy to perform operations on arrays of different shapes and sizes by automatically expanding the smaller array to match the shape of the larger array. This eliminates the need for explicit replication of data and simplifies the implementation of mathematical operations.

#### Key Features:

Dimension Compatibility: Broadcasting works when arrays have compatible shapes. Specifically, dimensions are compatible when:
They are equal, or
One of them is 1 (in which case, the smaller array is "stretched" to match the larger array).

Memory Efficiency: Broadcasting avoids unnecessary copying of data, which helps save memory and improves performance.

In [58]:
#Example

# Create a 1D array and a 2D array
a = np.array([1, 2, 3])       # Shape (3,)
b = np.array([[10], [20], [30]])  # Shape (3, 1)

# Broadcasting the addition
result = a + b  # a is treated as if it had shape (3, 3)
print(result)


[[11 12 13]
 [21 22 23]
 [31 32 33]]


#### Contributions to Efficient Array Operations

1. Performance Improvement

Reduced Execution Time: By using vectorized operations, NumPy can leverage low-level optimizations, leading to significant performance improvements, especially for large datasets.
Avoiding Python Overheads: Vectorization and broadcasting reduce the overhead of Python's interpreted nature by minimizing the number of loops and function calls.

2. Conciseness and Clarity

Simpler Code: Using vectorized operations and broadcasting results in cleaner and more understandable code. This makes it easier to write, read, and maintain code that performs complex mathematical operations.
Reduced Complexity: Complex data manipulation tasks become straightforward, allowing developers to focus more on problem-solving rather than on implementation details.

3. Scalability

Handling Large Datasets: Vectorization and broadcasting allow NumPy to handle large datasets efficiently, making it suitable for scientific computing, data analysis, and machine learning tasks.

# PRACTICAL QUESTIONS :-

## Q1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

### Answer:-

#### Here’s a 3x3 NumPy array with random integers between 1 and 100, along with its transposed version (where rows and columns are interchanged):

In [59]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Interchange (transpose) its rows and columns
transposed_array = np.transpose(array_3x3)

# Display the original and transposed arrays
print("Original Array:")
print(array_3x3)

print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[55 18 36]
 [94 40 11]
 [94 31 87]]

Transposed Array:
[[55 94 94]
 [18 40 31]
 [36 11 87]]


## Q2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

### Answer:-

In [60]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # Creates an array with elements from 0 to 9

# Print the original 1D array
print("Original 1D Array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## Q3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

### Answer:-

In [61]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Display the original and the bordered array
print("Original 4x4 Array:")
print(array_4x4)

print("\n6x6 Array with Border of Zeros:")
print(array_with_border)


Original 4x4 Array:
[[0.87818952 0.55205642 0.0707603  0.73839724]
 [0.66050596 0.40737244 0.99744728 0.39713491]
 [0.29325108 0.67391413 0.66409082 0.77637546]
 [0.62923847 0.60929458 0.43224587 0.35519271]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.87818952 0.55205642 0.0707603  0.73839724 0.        ]
 [0.         0.66050596 0.40737244 0.99744728 0.39713491 0.        ]
 [0.         0.29325108 0.67391413 0.66409082 0.77637546 0.        ]
 [0.         0.62923847 0.60929458 0.43224587 0.35519271 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


## Q4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

### Answer:-

In [62]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

# Display the resulting array
print(array_integers)


[10 15 20 25 30 35 40 45 50 55 60]


## Q5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

### Answer:-

In [63]:
import numpy as np

# Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
upper_case = np.char.upper(array_strings)
lower_case = np.char.lower(array_strings)
title_case = np.char.title(array_strings)
capitalize_case = np.char.capitalize(array_strings)

# Display the results of the transformations
print("Uppercase:", upper_case)
print("Lowercase:", lower_case)
print("Title Case:", title_case)
print("Capitalize Case:", capitalize_case)


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize Case: ['Python' 'Numpy' 'Pandas']


## Q6.Generate a NumPy array of words. Insert a space between each character of every word in the array.

### Answer:-

In [64]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words_array)

# Display the resulting array
print(spaced_words)


['p y t h o n' 'n u m p y' 'p a n d a s']


## Q7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

### Answer:-

In [65]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], 
                   [4, 5, 6]])

array2 = np.array([[10, 20, 30], 
                   [40, 50, 60]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Display the results of the operations
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[11 22 33]
 [44 55 66]]
Subtraction:
 [[ -9 -18 -27]
 [-36 -45 -54]]
Multiplication:
 [[ 10  40  90]
 [160 250 360]]
Division:
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


## Q8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

### Answer:-

In [66]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Display the identity matrix and its diagonal elements
print("5x5 Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


## Q9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

### Answer:-

In [67]:
import numpy as np

def is_prime(num):
    """Check if a number is prime."""
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display the random integers and the prime numbers
print("Random Integers:\n", random_integers)
print("\nPrime Numbers:", prime_numbers)


Random Integers:
 [ 180  380  655  581  713  893  167  454  857  127  407  242  146  703
    9  373  657  351   13  357  172 1000  654  410  628  464  901  312
  621  277  594  573  505  566   28  290  186  485  841   32  858  494
  952  133  204  214  611  428  883  800  543  116  939  606  586  868
  543  993  366   60  207  821  272  812  439  650  314  284  327  247
  148  343  984   52  205  806  585  536  984  542  150  208  893  508
  345  779  518  760  794  696  744   61  463  805  344  473  710  785
  975  280]

Prime Numbers: [np.int32(167), np.int32(857), np.int32(127), np.int32(373), np.int32(13), np.int32(277), np.int32(883), np.int32(821), np.int32(439), np.int32(61), np.int32(463)]


## Q10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

### Answer:-

In [68]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.uniform(low=15, high=35, size=30)  # Temperatures between 15 and 35 degrees

# Calculate weekly averages
# Reshape the daily temperatures into a 4x7 array for 4 weeks (28 days)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)

# Calculate the average for each week
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the daily temperatures and the weekly averages
print("Daily Temperatures:\n", daily_temperatures)
print("\nWeekly Averages:", weekly_averages)


Daily Temperatures:
 [25.28240652 26.69994988 33.14872987 32.77517923 17.15098772 20.33448028
 15.3966239  33.89472893 19.90762381 19.29418753 16.84254474 31.65019714
 24.31244717 19.64393148 31.09537651 21.33917543 21.9582905  30.408023
 26.16135407 28.13899694 23.79969301 20.40469415 25.65210176 26.35885684
 27.92640325 26.18295954 29.60446707 15.87127674 30.50305837 33.52804093]

Weekly Averages: [24.39833677 23.64938011 26.12870135 24.57153705]


# THANK YOU